<?php

declare(strict_types=1);

namespace F4\Pechkin\DataType;

use InvalidArgumentException;
use F4\Pechkin\DataType\{
    AbstractDataType,
    Animation,
    Audio,
    Chat,
    ChatBackground,
    ChatBoostAdded,
    ChatShared,
    Checklist,
    ChecklistTasksAdded,
    ChecklistTasksDone,
    Contact,
    Dice,
    DirectMessagePriceChanged,
    DirectMessagesTopic,
    Document,
    ExternalReplyInfo,
    ForumTopicClosed,
    ForumTopicCreated,
    ForumTopicEdited,
    ForumTopicReopened,
    Game,
    GeneralForumTopicHidden,
    GeneralForumTopicUnhidden,
    GiftInfo,
    Giveaway,
    GiveawayCompleted,
    GiveawayCreated,
    GiveawayWinners,
    InlineKeyboardMarkup,
    Invoice,
    LinkPreviewOptions,
    Location,
    MaybeInaccessibleMessage,
    MessageAutoDeleteTimerChanged,
    MessageEntity,
    MessageOrigin,
    PaidMediaInfo,
    PaidMessagePriceChanged,
    PassportData,
    PhotoSize,
    Poll,
    ProximityAlertTriggered,
    RefundedPayment,
    Sticker,
    Story,
    SuccessfulPayment,
    SuggestedPostApprovalFailed,
    SuggestedPostApproved,
    SuggestedPostDeclined,
    SuggestedPostInfo,
    SuggestedPostPaid,
    SuggestedPostRefunded,
    TextQuote,
    UniqueGiftInfo,
    User,
    UsersShared,
    Venue,
    Video,
    VideoChatEnded,
    VideoChatParticipantsInvited,
    VideoChatScheduled,
    VideoChatStarted,
    VideoNote,
    Voice,
    WebAppData,
    WriteAccessAllowed,
    Attribute\ArrayOf,
};

readonly class Message extends MaybeInaccessibleMessage
{
    public function __construct(
        public readonly int $message_id,
        public readonly int $date,
        public readonly Chat $chat,
        public readonly ?int $message_thread_id = null,
        public readonly ?DirectMessagesTopic $direct_messages_topic = null,
        public readonly ?User $from = null,
        public readonly ?Chat $sender_chat = null,
        public readonly ?int $sender_boost_count = null,
        public readonly ?User $sender_business_bot = null,
        public readonly ?string $business_connection_id = null,
        public readonly ?MessageOrigin $forward_origin = null,
        public readonly ?bool $is_topic_message = null,
        public readonly ?bool $is_automatic_forward = null,
        public readonly ?Message $reply_to_message = null,
        public readonly ?ExternalReplyInfo $external_reply = null,
        public readonly ?TextQuote $quote = null,
        public readonly ?Story $reply_to_story = null,
        public readonly ?int $reply_to_checklist_task_id = null,
        public readonly ?User $via_bot = null,
        public readonly ?int $edit_date = null,
        public readonly ?bool $has_protected_content = null,
        public readonly ?bool $is_from_offline = null,
        public readonly ?bool $is_paid_post = null,
        public readonly ?string $media_group_id = null,
        public readonly ?string $author_signature = null,
        public readonly ?int $paid_star_count = null,
        public readonly ?string $text = null,
        /** @var MessageEntity[]|null */
        #[ArrayOf(MessageEntity::class)]
        public readonly ?array $entities = null,
        public readonly ?LinkPreviewOptions $link_preview_options = null,
        public readonly ?SuggestedPostInfo $suggested_post_info = null,
        public readonly ?string $effect_id = null,
        public readonly ?Animation $animation = null,
        public readonly ?Audio $audio = null,
        public readonly ?Document $document = null,
        public readonly ?PaidMediaInfo $paid_media = null,
        /** @var PhotoSize[]|null */
        #[ArrayOf(PhotoSize::class)]
        public readonly ?array $photo = null,
        public readonly ?Sticker $sticker = null,
        public readonly ?Story $story = null,
        public readonly ?Video $video = null,
        public readonly ?VideoNote $video_note = null,
        public readonly ?Voice $voice = null,
        public readonly ?string $caption = null,
        /** @var MessageEntity[]|null */
        #[ArrayOf(MessageEntity::class)]
        public readonly ?array $caption_entities = null,
        public readonly ?bool $show_caption_above_media = null,
        public readonly ?bool $has_media_spoiler = null,
        public readonly ?Checklist $checklist = null,
        public readonly ?Contact $contact = null,
        public readonly ?Dice $dice = null,
        public readonly ?Game $game = null,
        public readonly ?Poll $poll = null,
        public readonly ?Venue $venue = null,
        public readonly ?Location $location = null,
        /** @var User[]|null */
        #[ArrayOf(User::class)]
        public readonly ?array $new_chat_members = null,
        public readonly ?User $left_chat_member = null,
        public readonly ?string $new_chat_title = null,
        /** @var PhotoSize[]|null */
        #[ArrayOf(PhotoSize::class)]
        public readonly ?array $new_chat_photo = null,
        public readonly ?bool $delete_chat_photo = null,
        public readonly ?bool $group_chat_created = null,
        public readonly ?bool $supergroup_chat_created = null,
        public readonly ?bool $channel_chat_created = null,
        public readonly ?MessageAutoDeleteTimerChanged $message_auto_delete_timer_changed = null,
        public readonly ?string $migrate_to_chat_id = null, // may not fit in a 32-bit integer
        public readonly ?string $migrate_from_chat_id = null, // may not fit in a 32-bit integer
        public readonly ?MaybeInaccessibleMessage $pinned_message = null,
        public readonly ?Invoice $invoice = null,
        public readonly ?SuccessfulPayment $successful_payment = null,
        public readonly ?RefundedPayment $refunded_payment = null,
        public readonly ?UsersShared $users_shared = null,
        public readonly ?ChatShared $chat_shared = null,
        public readonly ?GiftInfo $gift = null,
        public readonly ?UniqueGiftInfo $unique_gift = null,
        public readonly ?GiftInfo $gift_upgrade_sent = null,
        public readonly ?string $connected_website = null,
        public readonly ?WriteAccessAllowed $write_access_allowed = null,
        public readonly ?PassportData $passport_data = null,
        public readonly ?ProximityAlertTriggered $proximity_alert_triggered = null,
        public readonly ?ChatBoostAdded $boost_added = null,
        public readonly ?ChatBackground $chat_background_set = null,
        public readonly ?ChecklistTasksDone $checklist_tasks_done = null,
        public readonly ?ChecklistTasksAdded $checklist_tasks_added = null,
        public readonly ?DirectMessagePriceChanged $direct_message_price_changed = null,
        public readonly ?ForumTopicCreated $forum_topic_created = null,
        public readonly ?ForumTopicEdited $forum_topic_edited = null,
        public readonly ?ForumTopicClosed $forum_topic_closed = null,
        public readonly ?ForumTopicReopened $forum_topic_reopened = null,
        public readonly ?GeneralForumTopicHidden $general_forum_topic_hidden = null,
        public readonly ?GeneralForumTopicUnhidden $general_forum_topic_unhidden = null,
        public readonly ?GiveawayCreated $giveaway_created = null,
        public readonly ?Giveaway $giveaway = null,
        public readonly ?GiveawayWinners $giveaway_winners = null,
        public readonly ?GiveawayCompleted $giveaway_completed = null,
        public readonly ?PaidMessagePriceChanged $paid_message_price_changed = null,
        public readonly ?SuggestedPostApproved $suggested_post_approved = null,
        public readonly ?SuggestedPostApprovalFailed $suggested_post_approval_failed = null,
        public readonly ?SuggestedPostDeclined $suggested_post_declined = null,
        public readonly ?SuggestedPostPaid $suggested_post_paid = null,
        public readonly ?SuggestedPostRefunded $suggested_post_refunded = null,
        public readonly ?VideoChatScheduled $video_chat_scheduled = null,
        public readonly ?VideoChatStarted $video_chat_started = null,
        public readonly ?VideoChatEnded $video_chat_ended = null,
        public readonly ?VideoChatParticipantsInvited $video_chat_participants_invited = null,
        public readonly ?WebAppData $web_app_data = null,
        public readonly ?InlineKeyboardMarkup $reply_markup = null,

        // Undocumented property discoverd through API interaction
        public readonly ?User $forward_from = null,
        public readonly ?int $forward_date = null,
    )
    {
        if($this->date === 0) {
            throw new InvalidArgumentException('Date must be a positive integer');
        }
    }
}
